name       : gwenhywfar
version    : 4.20.0
release    : 1
source     :
    - https://github.com/aqbanking/gwenhywfar/archive/4.20.0.tar.gz : d0b73b60b5df080352ab23b88c589ab44f11b3e9a767b8368176cf42d5a95a83
license    : LGPL-2.1-only
component  : programming.library
summary    : A multi-platform helper library for networking, security applications and libraries
description: |
    Gwenhywfar is a multi-purpose library that provides useful functions such as configuration file handling, a full featured message generation and parsing engine, and an operating system abstraction layer. It is used by Libchipcard, AqBanking, QBankManager, OpenHBCI, AqMoney, and various other projects.
builddeps  :
      - pkgconfig(gnutls)
      - pkgconfig(gtk+-3.0)
      - libgcrypt-devel
setup      : |
    %reconfigure --with-guis="gtk3"
build      : |
    %make
install    : |
    %make_install
