name       : gwenhywfar
version    : 5.3.0
release    : 4
source     :
    - https://github.com/aqbanking/gwenhywfar/archive/5.3.0.tar.gz : f598225bb3a84b2199a066e118c9defd249c8ec6e45bef3b1efac516edaff068
license    : LGPL-2.1-only
component  : programming.library
summary    : A multi-platform helper library for networking, security applications and libraries
description: |
    Gwenhywfar is a multi-purpose library that provides useful functions such as configuration file handling, a full featured message generation and parsing engine, and an operating system abstraction layer. It is used by Libchipcard, AqBanking, QBankManager, OpenHBCI, AqMoney, and various other projects.
builddeps  :
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5QuickWidgets)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - libgcrypt-devel
setup      : |
    %reconfigure --with-guis="gtk3 qt5"
build      : |
    %make
install    : |
    %make_install
