name       : gwenhywfar
version    : 5.1.3
release    : 3
source     :
    - https://github.com/aqbanking/gwenhywfar/archive/5.1.3.tar.gz : 9701864bdddf13002aff5e953d25ded9787e602a7cc2faa9d0a8fd20bf724920
license    : LGPL-2.1-only
component  : programming.library
summary    : A multi-platform helper library for networking, security applications and libraries
description: |
    Gwenhywfar is a multi-purpose library that provides useful functions such as configuration file handling, a full featured message generation and parsing engine, and an operating system abstraction layer. It is used by Libchipcard, AqBanking, QBankManager, OpenHBCI, AqMoney, and various other projects.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5QuickWidgets)
    - pkgconfig(Qt5XmlPatterns)
    - libgcrypt-devel
setup      : |
    %reconfigure --with-guis="gtk3 qt5"
build      : |
    %make
install    : |
    %make_install
