name       : gwenhywfar
version    : 5.4.1
release    : 5
source     :
    - https://aquamaniac.de/rdm/attachments/download/344/gwenhywfar-5.4.1.tar.gz : fbfd403410e3c1cf7e2957738cf51c6a01ceeec6ab4d2f546512c255d3c08a9b
license    : LGPL-2.1-only
component  : programming.library
summary    : A multi-platform helper library for networking, security applications and libraries
description: |
    Gwenhywfar is a multi-purpose library that provides useful functions such as configuration file handling, a full featured message generation and parsing engine, and an operating system abstraction layer. It is used by Libchipcard, AqBanking, QBankManager, OpenHBCI, AqMoney, and various other projects.
builddeps  :
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5QuickWidgets)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - libgcrypt-devel
setup      : |
    %reconfigure --with-guis="gtk3 qt5"
build      : |
    %make
install    : |
    %make_install
